-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 15:18:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema essais2breizhvideo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `essais2breizhvideo` ;

-- -----------------------------------------------------
-- Schema essais2breizhvideo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `essais2breizhvideo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `essais2breizhvideo` ;

-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`actor` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`),
  INDEX `idx_actor_last_name` (`last_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`category` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`category` (
  `category_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`film` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` YEAR NULL DEFAULT NULL,
  `rental_duration` TINYINT UNSIGNED NOT NULL DEFAULT '3',
  `rental_rate` DECIMAL(4,2) NOT NULL DEFAULT '4.99',
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `rating` ENUM('G', 'PG', 'PG-13', 'R', 'NC-17') NULL DEFAULT 'G',
  `special_features` SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes') NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`),
  INDEX `idx_title` (`title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`film_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`film_actor` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`, `film_id`),
  INDEX `idx_fk_film_id` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_actor_actor`
    FOREIGN KEY (`actor_id`)
    REFERENCES `essais2breizhvideo`.`actor` (`actor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `essais2breizhvideo`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`film_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`film_category` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`film_category` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`,`category_id`),
  INDEX `fk_film_category_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `essais2breizhvideo`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_category_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `essais2breizhvideo`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`preferences` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`preferences` (
  `id` INT NOT NULL,
  `vote` INT NULL,
  `show_id` INT NOT NULL,
  `film_film_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preferences_show1_idx` (`show_id` ASC) VISIBLE,
  INDEX `fk_preferences_film1_idx` (`film_film_id` ASC) VISIBLE,
  CONSTRAINT `fk_preferences_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `essais2breizhvideo`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`village`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`village` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`village` (
  `idvillage` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  PRIMARY KEY (`idvillage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `essais2breizhvideo`.`show`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `essais2breizhvideo`.`show` ;

CREATE TABLE IF NOT EXISTS `essais2breizhvideo`.`show` (
  `id` INT NOT NULL,
  `diffusion` DATETIME NULL,
  `village_idvillage` INT NOT NULL,
  `film_film_id` SMALLINT UNSIGNED NOT NULL,
  `village_idvillage1` INT NOT NULL,
  `preferences_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_show_village_idx` (`village_idvillage` ASC) VISIBLE,
  INDEX `fk_show_film1_idx` (`film_film_id` ASC) VISIBLE,
  INDEX `fk_show_village1_idx` (`village_idvillage1` ASC) VISIBLE,
  INDEX `fk_show_preferences1_idx` (`preferences_id` ASC) VISIBLE,
  CONSTRAINT `fk_show_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `essais2breizhvideo`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_show_village1`
    FOREIGN KEY (`village_idvillage1`)
    REFERENCES `essais2breizhvideo`.`village` (`idvillage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_show_preferences1`
    FOREIGN KEY (`preferences_id`)
    REFERENCES `essais2breizhvideo`.`preferences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
